# Numpy

In [12]:
#alias a las librerias "as"
import numpy as np

a = [1,2,3],[4,5,6],[7,8,9]
b = ["name",False, 3.0, 4]
#convertir lista a tipo arreglo
numpyCorrecto = np.array(a)
print(a, "\n -----")
print(len(a), "\n -----")
print(numpyCorrecto, "\n -----")
print (type(numpyCorrecto), "\n -----") 
print (numpyCorrecto.shape) #obtener el tamaño de la matriz
print (numpyCorrecto[2][2]) #manera de acceder a la matriz con las coordenadas

([1, 2, 3], [4, 5, 6], [7, 8, 9]) 
 -----
3 
 -----
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 -----
<class 'numpy.ndarray'> 
 -----
(3, 3)
9


In [15]:

print(np.array(b))

print(numpyCorrecto[1][1],"\n -----")
numpyCorrecto [1][1] = 15
numpyCorrecto [2,2] = 19
print(numpyCorrecto)
print(numpyCorrecto.size)

['name' 'False' '3.0' '4']
15 
 -----
[[ 1  2  3]
 [ 4 15  6]
 [ 7  8 19]]
9


In [17]:
lista1dimensiones = [1,2,3] # lista de una dimension
lista2dimensiones = [[1,2,3],[4,5,6]] #dos dimensiones
lista3dimensiones = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] #tres dimensiones

numpy1dimension= np.array(lista1dimensiones)
numpy2dimension= np.array(lista2dimensiones)
numpy3dimension= np.array(lista3dimensiones)

print(numpy1dimension, "\n -----")
print(numpy1dimension.shape, "\n -----")


print(numpy2dimension, "\n -----")
print(numpy2dimension.shape, "\n -----")


print(numpy3dimension, "\n -----")
print(numpy3dimension.shape, "\n -----")



[1 2 3] 
 -----
(3,) 
 -----
[[1 2 3]
 [4 5 6]] 
 -----
(2, 3) 
 -----
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
 -----
(2, 2, 3) 
 -----
