# Numpy

In [2]:
#alias a las librerias "as"
import numpy as np

a = [1,2,3],[4,5,6],[7,8,9]
b = ["name",False, 3.0, 4]
#convertir lista a tipo arreglo
numpyCorrecto = np.array(a)
print(a, "\n -----")
print(len(a), "\n -----")
print(numpyCorrecto, "\n -----")
print (type(numpyCorrecto), "\n -----") 
print (numpyCorrecto.shape) #obtener el tamaño de la matriz
print (numpyCorrecto[2][2]) #manera de acceder a la matriz con las coordenadas

([1, 2, 3], [4, 5, 6], [7, 8, 9]) 
 -----
3 
 -----
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 -----
<class 'numpy.ndarray'> 
 -----
(3, 3)
9


In [3]:

print(np.array(b))

print(numpyCorrecto[1][1],"\n -----")
numpyCorrecto [1][1] = 15
numpyCorrecto [2,2] = 19
print(numpyCorrecto)
print(numpyCorrecto.size)

['name' 'False' '3.0' '4']
5 
 -----
[[ 1  2  3]
 [ 4 15  6]
 [ 7  8 19]]
9


In [4]:

lista1dimensiones = [1,2,3] # lista de una dimension
lista2dimensiones = [[1,2,3],[4,5,6]] #dos dimensiones
lista3dimensiones = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] #tres dimensiones

numpy1dimension= np.array(lista1dimensiones)
numpy2dimension= np.array(lista2dimensiones)
numpy3dimension= np.array(lista3dimensiones)

print(numpy1dimension, "\n -----")
print(numpy1dimension.shape, "\n -----")


print(numpy2dimension, "\n -----")
print(numpy2dimension.shape, "\n -----")


print(numpy3dimension, "\n -----")
print(numpy3dimension.shape, "\n -----")



[1 2 3] 
 -----
(3,) 
 -----
[[1 2 3]
 [4 5 6]] 
 -----
(2, 3) 
 -----
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
 -----
(2, 2, 3) 
 -----


In [5]:
array1 = np.arange (0, 18,2) #rango de vectores
#2 dimensiones
print(array1)
print(type(array1))
lista = range (0, 20)
print(lista)

print(array1.shape)

nuevasDimensiones = array1.reshape(3,3)
print (nuevasDimensiones)

#3 dimensiones
array2 = np.arange (0, 27,1)
Dimensiones3D = array2.reshape(3,3,3) # ".reshape" cambiar la dimensiones del vector
print (Dimensiones3D)

#ArrayTruncada = array2[0:9] se usan las llaves para mostrar el recorrido del primer vector
# len() es para imprimir el resultado de una lista

array3 = np.arange (0,9,1) # arange desde donde se quiere ir hasta el fin de donde se quiere y de cuanto en cuanto
array4 = np.linspace (0,10,9) #divide el recorrido de manera equitativa, según el valor que se quiera mostrar y muestra la cantidad deseada
print(array3)
print(array4)



[ 0  2  4  6  8 10 12 14 16]
<class 'numpy.ndarray'>
range(0, 20)
(9,)
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[0 1 2 3 4 5 6 7 8]
[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [7]:
valoresDelSeno = np.linspace (0, 2*np.pi, 10) # 2*np.pi es el código para llmar PI, ej 2 PI
print(valoresDelSeno)
seno = np.sin(valoresDelSeno)
print(seno)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


In [11]:
#multiplicación de matrices punto a punto
arreglo1 = np.array ([[1,2],[3,4]])
arreglo2 = np.array ([[4,3],[2,1]])
print (arreglo1*arreglo2)

[[4 6]
 [6 4]]


In [22]:
#multiplicación matricial 

print(arreglo1.dot(arreglo2),"\n--------")
A = arreglo1.dot(arreglo2)
B = arreglo2.dot(arreglo1)
print(A,"\n--------")
print(B,"\n--------")

[[ 8  5]
 [20 13]] 
--------
[[ 8  5]
 [20 13]] 
--------
[[13 20]
 [ 5  8]] 
--------


In [18]:
#suma de matrices
print(arreglo1+arreglo2, "\n--------")
# resta
print(arreglo1-arreglo2, "\n--------")
#elevación punto a punto
print(arreglo1**2,"\n--------")


[[5 5]
 [5 5]] 
--------
[[-3 -1]
 [ 1  3]] 
--------
[[ 1  4]
 [ 9 16]] 
--------


In [41]:
#concatenación de matrices verticalmente
ConcatenadaVertical1 = np.vstack((A,B))
ConcatenadaVertical2 = np.concatenate((A,B), axis = 0) # np.concatenate es para 
print (ConcatenadaVertical1,"\n--------\n",ConcatenadaVertical1)
print ("esta dimensión corresponde a una concatenación horizontal", ConcatenadaVertical1.shape, "\n")
#concatenación horizontal
ConcatenadaHorizontal1 = np.hstack((A,B))
ConcatenadaHorizontal2 = np.concatenate((A,B), axis = 1)
print (ConcatenadaHorizontal1,"\n--------\n",ConcatenadaHorizontal2,"\n--------\n")
print ("esta dimensión corresponde a una concatenación horizontal", ConcatenadaHorizontal1.shape, "\n")


[[ 8  5]
 [20 13]
 [13 20]
 [ 5  8]] 
--------
 [[ 8  5]
 [20 13]
 [13 20]
 [ 5  8]]
esta dimensión corresponde a una concatenación horizontal (4, 2) 

[[ 8  5 13 20]
 [20 13  5  8]] 
--------
 [[ 8  5 13 20]
 [20 13  5  8]] 
--------

esta dimensión corresponde a una concatenación horizontal (2, 4) 



In [43]:
#aumentar dimensiones
AumentarDimension = np.dstack((A,B))
print (AumentarDimension, "\n ----- \n")
print (AumentarDimension.shape)

[[[ 8 13]
  [ 5 20]]

 [[20  5]
  [13  8]]] 
 ----- 

(2, 2, 2)
